Add Kuttl (declarative E2E test) implem (#283)
* Add kuttl test scenario scaleUP (WIP)

* Test scale up with Kuttl

* Add crds in helm directory (casskop & multicasskop)

* Delete old beta crds

* Update doc

* Fix kuttl ScaleUp tests

* Fix helm install CRD override

* Add the necessary config for test parallelisation (random namespaces) & fix scaleup icarus assert incorrect matching

* Add ScaleDown step

* Rename test case folder

* Add Kuttl to circleci build

* Fix indent

* Fix makefile

* Update Makefile

* Update CircleCI kuttl integration

* Update config.yml

* Update config.yml

* Debug cci

* Fix config

* Add kuttl install circleci

* Install brew

* Install brew 2

* Fix brew

* fix brew

* Fix kuttl install

* Update config.yml

* Fix kuttl install in docker image

* Update Dockerfile

* Using binary kuttl for installation

* Using binary kuttl for installation2

* Update Dockerfile

* Update Dockerfile

* use cci for kuttl

* Update config.yml

* Update config.yml

* fix arg

* Add helm installation

* Add doc on "How to run kuttl tests" in developer guide

* Remove useless namespace option in doc

* Remove useless namespace option in doc (multi casskop)

* Fix backup & restore doc example

* Update and add spec of Backup & restore documentation

* Remove old helm 2 docs refs

* set cassandraCluster (with uppercase) in CRDs and definitions

* update CRD

* Fix tests

* Log secret validation error

* Update test with new typo

* FIX undo some wrong typo changes

* Fix test

* Applied review asked changes

* Rename test

* Update with merge of #282

* Remove unused topology

* Undo change post merge (distant repo not yet updated)

* Fix test

* Revert "Merge branch 'helm-3-install-crds' into bdd-testing"

This reverts commit bb84620a5be86a35281bb57d29652c12a25aa3ae, reversing
changes made to ba64023b824cd20d40be8c59f12f83fefe47f9c1.

* Remove event collect

Co-authored-by: Cyril Scetbon <cscetbon@gmail.com>

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -24,6 +24,10 @@ orbs:
             description: name of the test in e2e code
             type: string
             default: e2e code name
+          test_type:
+            description: type of test (e2e or kuttl)
+            type: string
+            default: e2e
           operatorDir:
             type: string
             description: relative path where the build must be run
@@ -74,21 +78,41 @@ orbs:
                 sudo chmod o+w /usr/local/bin/
                 wget -P /usr/local/bin/ https://storage.googleapis.com/kubernetes-release/release/${K8S_VERSION}/bin/linux/amd64/kubectl
                 chmod +x /usr/local/bin/kubectl
-          - attach_workspace:  # Attach artifact from workdir
+          - run:
+              name: Setup helm
+              command: curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
+          - run:
+                name: Setup kuttl
+                command: |
+                  set -x
+                  sudo chmod o+w /usr/local/bin/
+                  curl -L https://github.com/kudobuilder/kuttl/releases/download/v0.7.2/kubectl-kuttl_0.7.2_linux_x86_64 -o /usr/local/bin/kuttl
+                  chmod +x /usr/local/bin/kuttl
+          - attach_workspace: # Attach artifact from workdir
               at: /home/circleci
           # Acceptance test
           - run: # Run acceptance test through 'docker-e2e-test-fix-arg' makefile step
               name: Operator acceptance test
               no_output_timeout: 1200
               command: |
-                kubectl create namespace cassandra-e2e
-                ./tools/circleci-get-logs.sh&
-                make docker-e2e-test-fix-arg << parameters.test_name >> || {
-                kubectl get events --all-namespaces --sort-by .metadata.creationTimestamp ;
-                echo "Show Operator logs:"
-                cat operator.log
-                false;
-                }
+                if [ << parameters.test_type >> = "e2e" ]
+                then
+                  kubectl create namespace cassandra-e2e
+                  ./tools/circleci-get-logs.sh&
+                  make docker-e2e-test-fix-arg << parameters.test_name >> || {
+                    kubectl get events --all-namespaces --sort-by .metadata.creationTimestamp ;
+                    echo "Show Operator logs:"
+                    cat operator.log
+                    false;
+                  }
+                fi
+                if [ << parameters.test_type >> = "kuttl" ]
+                then
+                  make kuttl-test-fix-arg << parameters.test_name >> || {
+                    kubectl get events --all-namespaces --sort-by .metadata.creationTimestamp ;
+                    false;
+                  }
+                fi
   operator:
     # Parameters anchor
     .params_operator: &params_operator
@@ -125,7 +149,7 @@ orbs:
           - restore_cache: # If exist, restore dependencies libs download cache, from previous pipeline execution.
               keys: # Use checksum of go.sum to version cache.
                 - << parameters.operatorName >>-generate-{{ .Branch }}-{{ checksum "go.sum" }}
-          - attach_workspace:  # Attach artifact from workdir
+          - attach_workspace: # Attach artifact from workdir
               at: /home/circleci
           # Build steps
           - run:
@@ -156,135 +180,135 @@ orbs:
         <<: *params_operator
         <<: *job_operator
         steps:
-        - checkout:
-            path: /home/circleci/casskop
-        - setup_remote_docker # Creates a separate environment for each build for security.
-        - restore_cache: # If exist, restore dependencies libs download cache, from previous pipeline execution.
-            keys: # Use checksum of go.sum to version cache.
-              - << parameters.operatorName >>-build-{{ .Branch }}-{{ checksum "go.sum" }}
-        - attach_workspace:  # Attach artifact from workdir
-            at: /home/circleci
-        - run:
-            name: Build Operator
-            command: make build
-        - persist_to_workspace: # Create artifacts
-            root: /home/circleci
-            paths:
-              - << parameters.operatorDir >>/build/_output
-              - << parameters.operatorDir >>/vendor
-        - deploy:
-            name: Push image to Docker Hub
-            command: |
-              if [[ $(echo "$CIRCLE_BRANCH" | grep -c "pull") -gt 0 ]]; then
-                echo "This is a PR, we don't push to Hub."
-              else
-                docker login --username $DOCKERHUB_USER --password $DOCKERHUB_PASSWORD
-                make push
-              fi
-        - save_cache:
-            name: Save build artifacts in cache
-            key: << parameters.operatorName >>-build-{{ .Branch }}-{{ checksum "go.sum" }}
-            paths:
-              - build/_output
-              - vendor
+          - checkout:
+              path: /home/circleci/casskop
+          - setup_remote_docker # Creates a separate environment for each build for security.
+          - restore_cache: # If exist, restore dependencies libs download cache, from previous pipeline execution.
+              keys: # Use checksum of go.sum to version cache.
+                - << parameters.operatorName >>-build-{{ .Branch }}-{{ checksum "go.sum" }}
+          - attach_workspace: # Attach artifact from workdir
+              at: /home/circleci
+          - run:
+              name: Build Operator
+              command: make build
+          - persist_to_workspace: # Create artifacts
+              root: /home/circleci
+              paths:
+                - << parameters.operatorDir >>/build/_output
+                - << parameters.operatorDir >>/vendor
+          - deploy:
+              name: Push image to Docker Hub
+              command: |
+                if [[ $(echo "$CIRCLE_BRANCH" | grep -c "pull") -gt 0 ]]; then
+                  echo "This is a PR, we don't push to Hub."
+                else
+                  docker login --username $DOCKERHUB_USER --password $DOCKERHUB_PASSWORD
+                  make push
+                fi
+          - save_cache:
+              name: Save build artifacts in cache
+              key: << parameters.operatorName >>-build-{{ .Branch }}-{{ checksum "go.sum" }}
+              paths:
+                - build/_output
+                - vendor
 
       # Unit test job, will execute makefile 'unit-test-with-vendor' step
       unit-test:
         <<: *params_operator
         <<: *job_operator
         steps:
-        - checkout:
-            path: /home/circleci/casskop
-        - attach_workspace:  # Attach artifact from workdir
-            at: /home/circleci
-        # Unit tests steps
-        - run:
-            name: Unit Tests
-            command: make unit-test-with-vendor
-        # Artifacts definitions
-        - store_artifacts: # Store unit test coverage reports
-            path: coverage.html
-        - persist_to_workspace:
-            root: /home/circleci
-            paths:
-              - << parameters.operatorDir >>/coverage.out
-              - << parameters.operatorDir >>/test-report.out
+          - checkout:
+              path: /home/circleci/casskop
+          - attach_workspace: # Attach artifact from workdir
+              at: /home/circleci
+          # Unit tests steps
+          - run:
+              name: Unit Tests
+              command: make unit-test-with-vendor
+          # Artifacts definitions
+          - store_artifacts: # Store unit test coverage reports
+              path: coverage.html
+          - persist_to_workspace:
+              root: /home/circleci
+              paths:
+                - << parameters.operatorDir >>/coverage.out
+                - << parameters.operatorDir >>/test-report.out
 
       # Dgoss tests job, will execute make 'dgoss-bootstrap'
       docker-dgoss-test:
         <<: *params_operator
         <<: *job_operator
         steps:
-        - checkout:
-            path: /home/circleci/casskop
-        - setup_remote_docker
-        - attach_workspace:  # Attach artifact from workdir
-            at: /home/circleci
-        # Dgoss tests steps
-        - run: # Run test wich enable to validate bootstrap image.
-            name: Dgoss tests
-            command: |
-              curl -L https://raw.githubusercontent.com/aelsabbahy/goss/master/extras/dgoss/dgoss -o /usr/local/bin/dgoss
-              chmod +rx /usr/local/bin/dgoss
-              curl -L https://github.com/aelsabbahy/goss/releases/download/v0.3.6/goss-linux-amd64 -o /usr/local/bin/goss
-              chmod +rx /usr/local/bin/goss
-              export GOSS_PATH=/usr/local/bin/goss
-              export GOSS_FILES_STRATEGY=cp
-              make dgoss-bootstrap
+          - checkout:
+              path: /home/circleci/casskop
+          - setup_remote_docker
+          - attach_workspace: # Attach artifact from workdir
+              at: /home/circleci
+          # Dgoss tests steps
+          - run: # Run test wich enable to validate bootstrap image.
+              name: Dgoss tests
+              command: |
+                curl -L https://raw.githubusercontent.com/aelsabbahy/goss/master/extras/dgoss/dgoss -o /usr/local/bin/dgoss
+                chmod +rx /usr/local/bin/dgoss
+                curl -L https://github.com/aelsabbahy/goss/releases/download/v0.3.6/goss-linux-amd64 -o /usr/local/bin/goss
+                chmod +rx /usr/local/bin/goss
+                export GOSS_PATH=/usr/local/bin/goss
+                export GOSS_FILES_STRATEGY=cp
+                make dgoss-bootstrap
 
       # Reporting step, will run sonar report from scan.
       report:
         <<: *params_operator
         <<: *job_operator
         steps:
-        - checkout:
-            path: /home/circleci/casskop
-        - attach_workspace:
-            at: /home/circleci
-        - restore_cache: # If exist, restore dependencies libs download cache, from previous pipeline execution.
-            name: Restore SonarQube Scanner
-            keys:
-              - sonar-scanner-3.3.0.1492-linux
-        # Sonar steps
-        - run:
-            name: Download SonarQube Scanner
-            command: |
-              chmod +x /home/circleci/casskop/.circleci/install_sonar-scanner.sh
-              /home/circleci/casskop/.circleci/install_sonar-scanner.sh
-        - save_cache: # Cache sonar download
-            name: Cache SonarQube Scanner
-            key: sonar-scanner-3.3.0.1492-linux
-            paths:
-              - sonar-scanner-3.3.0.1492-linux
-              - /home/circleci/<< parameters.operatorDir >>/.sonar
-        - run: # Run sonar scan
-            name: Sonarcloud Scan
-            command: |
-              ./sonar-scanner-3.3.0.1492-linux/bin/sonar-scanner -X \
-              -Dsonar.projectName=<< parameters.operatorName >> \
-              -Dsonar.projectKey=${SONAR_PROJECT} \
-              -Dsonar.login=${SONAR_TOKEN} \
-              -Dsonar.branch.name=${CIRCLE_BRANCH} \
-              -Dsonar.organization=${SONAR_ORGANISATION} \
-              -Dsonar.host.url=https://sonarcloud.io \
-              -Dsonar.projectBaseDir=/home/circleci/<< parameters.operatorDir >> \
-              -Dsonar.sources=. \
-              -Dsonar.sources.inclusions="**/**.go" \
-              -Dsonar.exclusions="**/*_test.go,**/vendor/**,**/sonar-scanner-3.3.0.1492-linux/**,**docs/**" \
-              -Dsonar.coverage.exclusions="**/vendor/**,**/test/**,**docs/**" \
-              -Dsonar.tests=. \
-              -Dsonar.language=go \
-              -Dsonar.sourceEncoding=UTF-8 \
-              -Dsonar.test.inclusions="**/**_test.go" \
-              -Dsonar.test.exclusions="**/vendor/**" \
-              -Dsonar.go.coverage.reportPaths=coverage.out \
-              -Dsonar.go.tests.reportPaths=test-report.out \
-              -Dsonar.coverage.dtdVerification=false \
-              -Dsonar.log.level=INFO
-              cat -n .scannerwork/report-task.txt
-        # Artifacts definitions
-        - store_test_results: # Store sonar scan reports
-            path: reports
+          - checkout:
+              path: /home/circleci/casskop
+          - attach_workspace:
+              at: /home/circleci
+          - restore_cache: # If exist, restore dependencies libs download cache, from previous pipeline execution.
+              name: Restore SonarQube Scanner
+              keys:
+                - sonar-scanner-3.3.0.1492-linux
+          # Sonar steps
+          - run:
+              name: Download SonarQube Scanner
+              command: |
+                chmod +x /home/circleci/casskop/.circleci/install_sonar-scanner.sh
+                /home/circleci/casskop/.circleci/install_sonar-scanner.sh
+          - save_cache: # Cache sonar download
+              name: Cache SonarQube Scanner
+              key: sonar-scanner-3.3.0.1492-linux
+              paths:
+                - sonar-scanner-3.3.0.1492-linux
+                - /home/circleci/<< parameters.operatorDir >>/.sonar
+          - run: # Run sonar scan
+              name: Sonarcloud Scan
+              command: |
+                ./sonar-scanner-3.3.0.1492-linux/bin/sonar-scanner -X \
+                -Dsonar.projectName=<< parameters.operatorName >> \
+                -Dsonar.projectKey=${SONAR_PROJECT} \
+                -Dsonar.login=${SONAR_TOKEN} \
+                -Dsonar.branch.name=${CIRCLE_BRANCH} \
+                -Dsonar.organization=${SONAR_ORGANISATION} \
+                -Dsonar.host.url=https://sonarcloud.io \
+                -Dsonar.projectBaseDir=/home/circleci/<< parameters.operatorDir >> \
+                -Dsonar.sources=. \
+                -Dsonar.sources.inclusions="**/**.go" \
+                -Dsonar.exclusions="**/*_test.go,**/vendor/**,**/sonar-scanner-3.3.0.1492-linux/**,**docs/**" \
+                -Dsonar.coverage.exclusions="**/vendor/**,**/test/**,**docs/**" \
+                -Dsonar.tests=. \
+                -Dsonar.language=go \
+                -Dsonar.sourceEncoding=UTF-8 \
+                -Dsonar.test.inclusions="**/**_test.go" \
+                -Dsonar.test.exclusions="**/vendor/**" \
+                -Dsonar.go.coverage.reportPaths=coverage.out \
+                -Dsonar.go.tests.reportPaths=test-report.out \
+                -Dsonar.coverage.dtdVerification=false \
+                -Dsonar.log.level=INFO
+                cat -n .scannerwork/report-task.txt
+          # Artifacts definitions
+          - store_test_results: # Store sonar scan reports
+              path: reports
 
       publish-helm:
         <<: *params_operator
@@ -310,22 +334,22 @@ jobs:
     steps:
       - checkout:
           path: /home/circleci/casskop
-#      - restore_cache:
-#          name: Restore yarn Scanner
-#          keys:
-#            - root-yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
-#            # Fallback in case checksum fails
-#            - root-yarn-{{ .Branch }}-
-#      - run:
-#          name: root-yarn
-#          command: |
-#              yarn install --non-interactive --cache-folder ~/.cache/yarn
-#      - save_cache:
-#          name: Save yarn cache
-#          paths:
-#            - node_modules
-#            - ~/.cache/yarn
-#          key: root-yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
+      #      - restore_cache:
+      #          name: Restore yarn Scanner
+      #          keys:
+      #            - root-yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
+      #            # Fallback in case checksum fails
+      #            - root-yarn-{{ .Branch }}-
+      #      - run:
+      #          name: root-yarn
+      #          command: |
+      #              yarn install --non-interactive --cache-folder ~/.cache/yarn
+      #      - save_cache:
+      #          name: Save yarn cache
+      #          paths:
+      #            - node_modules
+      #            - ~/.cache/yarn
+      #          key: root-yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
       - run:
           name: deploy
           command: |
@@ -340,12 +364,12 @@ jobs:
 
 # Anchors
 ## Filters anchors
-.everytime_filter : &everytime_filter
+.everytime_filter: &everytime_filter
   filters:
     tags:
       only: /.*/
 
-.canonical_repo_filter : &canonical_repo_filter
+.canonical_repo_filter: &canonical_repo_filter
   filters:
     tags:
       only: /.*/
@@ -375,7 +399,7 @@ jobs:
     # ignore any commit on any branch by default
     branches:
       only:
-      - master
+        - master
 
 ## Parameters anchors
 .params_multicasskop: &params_multicasskop
@@ -465,6 +489,14 @@ workflows:
             - build-casskop
           <<: *ignore_fork_pr_filter
 
+      - k3d/e2e-orb:
+          name: kuttl-test ScaleUpAndDown
+          test_name: ScaleUpAndDown # Has be be the same as the TestCase (folder) in Kuttl directory
+          test_type: kuttl
+          requires:
+            - build-casskop
+          <<: *ignore_fork_pr_filter
+
       - operator/publish-helm:
           name: publish-helm-orange-incubator-casskop
           requires:
@@ -474,7 +506,7 @@ workflows:
       - deploy-website:
           name: deploy-website
           requires:
-             - report-casskop
+            - report-casskop
           <<: *website_publish
 
   # MultiCassKop operator workflow.
